import type { Metadata } from "next";
import "./globals.css";
import { Jost } from '@next/font/google';

const jost = Jost({
  subsets: ['latin'], // Add other subsets if needed
  // weights: [400, 500, 600], // Define the font weights you want to use
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.className}`}
      >
        {children}
      </body>
    </html>
  );
}
